# Generated by Django 4.1.6 on 2023-02-15 05:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsdescriptionhifi',
            options={'verbose_name': 'Аудио Компонент', 'verbose_name_plural': 'Аудио Компоненты'},
        ),
        migrations.AlterModelOptions(
            name='productsdescriptionvinyl',
            options={'verbose_name': 'Виниловая пластинка', 'verbose_name_plural': 'Виниловые пластинки'},
        ),
        migrations.AlterField(
            model_name='productsdescriptionvinyl',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='VinylPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='photos/vinyls/vinyl_photos/%Y/%m/%d/')),
                ('vinyl_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsdescriptionvinyl')),
            ],
            options={
                'verbose_name': 'Vinyl photo',
                'verbose_name_plural': 'Vinyl photos',
            },
        ),
    ]
