# Generated by Django 4.1.6 on 2023-03-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productsdescriptionhifi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsdescriptionvinyl',
            options={'ordering': ['-create_date'], 'verbose_name': 'Виниловая пластинка', 'verbose_name_plural': 'Виниловые пластинки'},
        ),

    ]
