# Generated by Django 4.1.6 on 2023-03-13 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productsdescriptionvinyl_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VinylPhoto',
        ),
    ]
