# Generated by Django 4.1.6 on 2023-03-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_vinylphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
