# Generated by Django 4.1.6 on 2023-03-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_vinylphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VinylPhoto',
        ),
    ]
